version: '3.3'

networks:
  simple-talk:
    driver: bridge

services:
  simple-talk_app:
    container_name: simple-talk_app
    image: elixir:alpine
    ports:
      - 4000:4000
      - 4001:4001
    volumes:
      - .:/home/app
    depends_on:
      - simple-talk_db
    networks:
      - simple-talk

  simple-talk_db:
    container_name: simple-talk_db
    image: postgres:12
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres/data:/var/lib/pgsql/data
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: langco_stream_dev
      PGDATA: /var/lib/pgsql/data
    networks:
      - simple-talk